#!/usr/bin/env ruby

require_relative '../init'

require 'component_host'

ComponentHost.start('welcome-email-component') do |host|
  welcome_email_component_initiator = RegistrationComponent::Start.build
  host.register(welcome_email_component_initiator)
end
